resources = {
    "es": {
        "default_messages": {
            "message_cancel_start_bets_head": "⚠️ *Rechazo de análisis*",
            "message_cancel_start_bets_body_1": "La estrategia",
            "message_cancel_start_bets_body_2": "no siguió un patrón\\.",
            "message_cancel_start_bets_foot": "Iniciando nuevo análisis…",

            "message_win_bet_head": "🎉 *¡ACIERTO\\!* 🥳💰💵🤑🔮",
            "message_win_bet_body": "💵 Resultado: Apuesta Ganada en ",
            "message_win_bet_foot": "💸 ¡Vamos por más\\! ¡Multipliquemos nuestras ganancias\\! 💰💰💰",

            "message_lose_bet": (
                "❌ *Apuesta Perdida*",
                "Resultado: Apuesta no acertada\\. Iniciando nuevo análisis…",
            ),

            "message_alert_bet_head": "🎲 *¡ATENCIÓN\\!* 🚨🚨",
            "message_alert_bet_body": "🎯 Analizando mesa para posible apuesta en",
            "message_alert_bet_foot": "📊 Esperando resultados… ⏳",

            "message_confirmed_start_bet_head": "✅ *¡CONFIRMADO\\!*",
            "message_confirmed_start_bet_body": "Apostar en",
            "message_confirmed_start_bet_foot": "🔐 Proteger el 0\\.",
            
            "message_cases_head": "🎲 *¡ATENCIÓN\\!* 🚨",
            "message_cases_body": "se volvió a repetir\\.",
            "message_cases_foot_double": "Dobla tu apuesta anterior\\.",
            "message_cases_foot_triple": "Triplica tu apuesta anterior\\.",
            "message_cases_foot": "📊 Esperando resultados… ⏳✨",
            "report_wins_loses_daily_head": "🚀 Resultado del día",
            "report_wins_loses_daily_body": "🎯 Aciertos",
            "report_wins_loses_daily_foot": "% de las veces",
            "restart_counter": "⏰ Reiniciando contador…"
        },
        "entities_strategies": {
            "for_zones": "Zona",
            "red_and_black": "Color",
            "even_and_odd": "Número",
            "two_groups": "Grupo",
        },
        "names_strategies": {
            "for_zones": "'por zonas'",
            "red_and_black": "'rojo y negro'",
            "even_and_odd": "'par e impar'",
            "two_groups": "'dos grupos'",
        },
    },
    "en": {
        "default_messages": {
            "message_cancel_start_bets_head": "⚠️ *Analysis Rejected*",
            "message_cancel_start_bets_body_1": "The strategy",
            "message_cancel_start_bets_body_2": "did not follow a pattern\\.",
            "message_cancel_start_bets_foot": "Starting a new analysis…",
            "message_win_bet_head": "🎉 *WIN\\!* 🥳💰💵🤑🔮",
            "message_win_bet_body": "💵 Result: Bet Won on ",
            "message_win_bet_foot": "💸 Let’s go for more\\! Let’s multiply our winnings\\! 💰💰💰",
            "message_lose_bet": (
                "❌ *Bet Lost*",
                "Result: Bet not successful\\. Starting a new analysis…",
            ),
            "message_alert_bet_head": "🎲 *ATTENTION\\!* 🚨🚨",
            "message_alert_bet_body": "🎯 Analyzing table for a possible bet on",
            "message_alert_bet_foot": "📊 Waiting for results… ⏳",
            "message_confirmed_start_bet_head": "✅ *CONFIRMED\\!*",
            "message_confirmed_start_bet_body": "Bet on",
            "message_confirmed_start_bet_foot": "🔐 Protect the 0\\.",
            "message_cases_head": "🎲 *ATTENTION\\!* 🚨",
            "message_cases_body": "has repeated\\.",
            "message_cases_foot_double": "Double your previous bet\\.",
            "message_cases_foot_triple": "Triple your previous bet\\.",
            "message_cases_foot": "📊 Waiting for results… ⏳✨",
            "report_wins_loses_daily_head": "🚀 Daily Result",
            "report_wins_loses_daily_body": "🎯 Wins",
            "report_wins_loses_daily_foot": "% of the time",
            "restart_counter": "⏰ Resetting counter..."
        },
        "entities_strategies": {
            "for_zones": "Zone",
            "red_and_black": "Color",
            "even_and_odd": "Number",
            "two_groups": "Group",
        },
        "names_strategies": {
            "for_zones": "'by zones'",
            "red_and_black": "'red and black'",
            "even_and_odd": "'even and odd'",
            "two_groups": "'two groups'",
        },
    },
    "fr": {
        "default_messages": {
            "message_cancel_start_bets_head": "⚠️ *Analyse rejetée*",
            "message_cancel_start_bets_body_1": "La stratégie",
            "message_cancel_start_bets_body_2": "n'a pas suivi un modèle\\.",
            "message_cancel_start_bets_foot": "Nouvelle analyse en cours…",
            "message_win_bet_head": "🎉 *VICTOIRE\\!* 🥳💰💵🤑🔮",
            "message_win_bet_body": "💵 Résultat: Pari gagné sur ",
            "message_win_bet_foot": "💸 Allons\\-y pour plus\\! Multipliant nos gains\\! 💰💰💰",
            "message_lose_bet": (
                "❌ *Pari perdu*",
                "Résultat : Pari non réussi\\. Nouvelle analyse en cours…",
            ),
            "message_alert_bet_head": "🎲 *ATTENTION\\!* 🚨🚨",
            "message_alert_bet_body": "🎯 Analyse de la table pour un pari possible sur",
            "message_alert_bet_foot": "📊 En attente des résultats… ⏳",
            "message_confirmed_start_bet_head": "✅ *CONFIRMÉ\\!*",
            "message_confirmed_start_bet_body": "Parier sur",
            "message_confirmed_start_bet_foot": "🔐 Protéger le 0\\.",
            "message_cases_head": "🎲 *ATTENTION\\!* 🚨",
            "message_cases_body": "s'est répété\\.",
            "message_cases_foot_double": "Doublez votre pari précédent\\.",
            "message_cases_foot_triple": "Triplez votre pari précédent\\.",
            "message_cases_foot": "📊 En attente des résultats… ⏳✨",
            "report_wins_loses_daily_head": "🚀 Résultat du jour",
            "report_wins_loses_daily_body": "🎯 Gains",
            "report_wins_loses_daily_foot": "% du temps",
            "restart_counter": "⏰ Remise à zéro du compteur..."
        },
        "entities_strategies": {
            "for_zones": "Zone",
            "red_and_black": "Couleur",
            "even_and_odd": "Nombre",
            "two_groups": "Groupe",
        },
        "names_strategies": {
            "for_zones": "'par zones'",
            "red_and_black": "'rouge et noir'",
            "even_and_odd": "'pair et impair'",
            "two_groups": "'deux groupes'",
        },
    },
}
