// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.user_id", "d9495ae6-3880-4ca6-be72-22df43e1a1be");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.allowUpdatesForUnelevatedInstallations", true);
user_pref("app.update.background.lastInstalledTaskVersion", 4);
user_pref("app.update.background.rolledout", true);
user_pref("app.update.checkInstallTime", false);
user_pref("app.update.disabledForTesting", true);
user_pref("app.update.download.attempts", 0);
user_pref("app.update.langpack.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1730838326);
user_pref("app.update.lastUpdateTime.background-update-timer", 1730859926);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1730868391);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1730838326);
user_pref("app.update.lastUpdateTime.region-update-timer", 1730838326);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1730838454);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1730838326);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1730838355);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 1730841926);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1730838326);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.newtabpage.activity-stream.asrouter.debugLogLevel", "error");
user_pref("browser.newtabpage.activity-stream.impressionId", "{d0b7acd2-a626-400b-823d-c8d0bb0c77cf}");
user_pref("datareporting.healthreport.documentServerURI", "http://%(server)s/dummy/healthreport/");
user_pref("datareporting.healthreport.logging.consoleEnabled", false);
user_pref("datareporting.healthreport.service.enabled", false);
user_pref("datareporting.healthreport.service.firstRun", false);
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyBypassNotification", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1730838297926");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("messaging-system.log", "error");
user_pref("services.settings.loglevel", "error");
user_pref("services.settings.server", "data:,#remote-settings-dummy/v1");
user_pref("toolkit.backgroundtasks.loglevel", "error");
user_pref("toolkit.startup.last_success", 1730897027);
user_pref("toolkit.telemetry.cachedClientID", "e7683607-281a-400a-a2ac-445b7046492c");
user_pref("toolkit.telemetry.cachedProfileGroupID", "ce340e64-7a8f-48e7-9bff-b4b125131e7e");
